# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tsuru < Formula
  desc "tsuru-client is a tsuru command line tool for application developers."
  homepage "https://docs.tsuru.io/stable/"
  version "1.13.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tsuru/tsuru-client/releases/download/1.13.0/tsuru_1.13.0_macOS_amd64.tar.gz"
      sha256 "2f297aff7645903573c956ef5290fee111cd73874d87e9c72c4abea1693ada0b"

      def install
        bin.install "tsuru"
        bash_completion.install "misc/bash-completion" => "tsuru"
        zsh_completion.install "misc/zsh-completion" => "tsuru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tsuru/tsuru-client/releases/download/1.13.0/tsuru_1.13.0_macOS_arm64.tar.gz"
      sha256 "5db569e1b5420a6d37288aef91187bb9cc87aa8e7ff7e66f15bcb53a9c645ec0"

      def install
        bin.install "tsuru"
        bash_completion.install "misc/bash-completion" => "tsuru"
        zsh_completion.install "misc/zsh-completion" => "tsuru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tsuru/tsuru-client/releases/download/1.13.0/tsuru_1.13.0_linux_arm64.tar.gz"
      sha256 "0b4ec7ac4e5a3b0f67bdebfe01558ba8ec951d1696a26481716fef1e622c7b76"

      def install
        bin.install "tsuru"
        bash_completion.install "misc/bash-completion" => "tsuru"
        zsh_completion.install "misc/zsh-completion" => "tsuru"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tsuru/tsuru-client/releases/download/1.13.0/tsuru_1.13.0_linux_amd64.tar.gz"
      sha256 "19937eaa8ca1fb41c708ce81a70296394850aa6c19bcd7a91d6c9cfba53a2ebd"

      def install
        bin.install "tsuru"
        bash_completion.install "misc/bash-completion" => "tsuru"
        zsh_completion.install "misc/zsh-completion" => "tsuru"
      end
    end
  end
end
